### ISSUE TITLE
Mapa mental de conjuntos

### ISSUE THREAD

**Issue by Alondra-oss** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Alondra-oss#2]
[CONJUNTOS Y RELACIONES (mapa mental). (1).pdf](https://github.com/user-attachments/files/17090949/CONJUNTOS.Y.RELACIONES.mapa.mental.1.pdf)

**Comment by Evelyn-sj13** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:5/5
Referencias:5/5
Calificación Final:20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
